production:
  adapter: mysql2
  database: IkuraCloud
  host: localhost
  pool: 5
  username: root
  password: group1
  encoding: utf8

development:
  adapter: mysql2
  database: IkuraCloud
  host: localhost
  pool: 5
  username: root
  password: group1
  encoding: utf8
