# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'grape'

gem 'grape-entity'

gem 'sinatra'

gem 'sinatra-formkeeper'

gem "sinatra-contrib"

gem 'formkeeper-japanese'

gem 'bunny'

gem "activerecord", "< 5.0.0"

gem 'mysql2'
